// Type definitions
export interface Skill {
	id: string;
	name: string;
	description: string;
	category: string;
	type: "atlassian" | "third-party";
	icon: string; // Icon identifier from ADS icon library
	collection: string; // Collection name (Teamwork, Strategy, Service, Software, Product, General)
	fill: string; // Color token for icon fill (e.g., "color.icon.accent.blue")
	tags: string[]; // Array of tags for search and categorization
	appLogo?: string; // Only for third-party skills
	appName?: string; // Only for third-party skills
}

export interface SkillCategory {
	id: string;
	name: string;
	description?: string;
}

export interface SkillsData {
	categories: SkillCategory[];
	skills: Skill[];
}

// Data
export const skillsData: SkillsData = {
	categories: [
		{
			id: "content-management",
			name: "Content Management",
			description: "Skills for creating, editing, and managing content",
		},
		{
			id: "communication",
			name: "Communication",
			description: "Skills for messaging and collaboration",
		},
		{
			id: "productivity",
			name: "Productivity",
			description: "Skills to enhance workflow and efficiency",
		},
		{
			id: "analysis",
			name: "Analysis",
			description: "Skills for data analysis and insights",
		},
		{
			id: "project-management",
			name: "Project Management",
			description: "Skills for planning, tracking, and executing projects",
		},
		{
			id: "administrative-tools",
			name: "Administrative Tools",
			description: "Skills for administrative tasks and workflows",
		},
		{
			id: "content-communication",
			name: "Content & Communication",
			description: "Skills for content creation and team communication",
		},
		{
			id: "data-analytics",
			name: "Data & Analytics",
			description: "Skills for data analysis and business intelligence",
		},
		{
			id: "software-development",
			name: "Software Development",
			description: "Skills for building and deploying software",
		},
		{
			id: "it-support-service",
			name: "IT Support & Service",
			description: "Skills for IT support and service management",
		},
		{
			id: "design-diagramming",
			name: "Design and Diagramming",
			description: "Skills for design and visual documentation",
		},
		{
			id: "security-compliance",
			name: "Security & Compliance",
			description: "Skills for security and compliance management",
		},
		{
			id: "hr-team-building",
			name: "HR & Team Building",
			description: "Skills for human resources and team development",
		},
		{
			id: "sales-customer-relations",
			name: "Sales & Customer Relations",
			description: "Skills for sales and customer relationship management",
		},
	],
	skills: [
		{
			id: "summarize-page",
			name: "Summarize page",
			description: "Get the key points quickly",
			category: "content-management",
			type: "atlassian",
			icon: "align-text-left",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["summarize", "content", "quick-read"],
		},
		{
			id: "summarize-changes",
			name: "Summarize changes",
			description: "See what's been updated",
			category: "content-management",
			type: "atlassian",
			icon: "clock",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["summarize", "changes", "updates"],
		},
		{
			id: "change-tone",
			name: "Change tone",
			description: "Adjust the mood and style",
			category: "content-management",
			type: "atlassian",
			icon: "microphone",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["tone", "writing", "style"],
		},
		{
			id: "translate",
			name: "Translate",
			description: "Convert text to another language",
			category: "content-management",
			type: "atlassian",
			icon: "translate",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["translation", "language", "multilingual"],
		},
		{
			id: "expand-text",
			name: "Expand text",
			description: "Make your content more detailed",
			category: "content-management",
			type: "atlassian",
			icon: "expand-horizontal",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["expand", "detail", "verbose"],
		},
		{
			id: "make-shorter",
			name: "Make shorter",
			description: "Condense your content concisely",
			category: "content-management",
			type: "atlassian",
			icon: "shrink-horizontal",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["shorten", "concise", "brief"],
		},
		{
			id: "fix-grammar",
			name: "Fix grammar",
			description: "Correct spelling and grammar",
			category: "content-management",
			type: "atlassian",
			icon: "text-spellcheck",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["grammar", "spellcheck", "editing"],
		},
		{
			id: "send-message",
			name: "Send message",
			description: "Share your thoughts instantly",
			category: "communication",
			type: "atlassian",
			icon: "send",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["message", "communication", "share"],
		},
		{
			id: "schedule-meeting",
			name: "Schedule meeting",
			description: "Set up time with team members",
			category: "communication",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["meeting", "calendar", "schedule"],
		},
		{
			id: "create-poll",
			name: "Create poll",
			description: "Get quick feedback from team",
			category: "communication",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["poll", "survey", "feedback"],
		},
		{
			id: "share-screen",
			name: "Share screen",
			description: "Present your screen to others",
			category: "communication",
			type: "atlassian",
			icon: "screen-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["screen", "presentation", "share"],
		},
		{
			id: "record-audio-note",
			name: "Record audio note",
			description: "Create voice message notes",
			category: "communication",
			type: "atlassian",
			icon: "audio",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["audio", "voice", "recording"],
		},
		{
			id: "turn-into-loom",
			name: "Turn into Loom video",
			description: "Create engaging video content",
			category: "communication",
			type: "third-party",
			icon: "video",
			collection: "General",
			fill: "color.icon.subtlest",
			appName: "Loom",
			appLogo: "https://cdn.loom.com/assets/img/favicons/favicon-96x96.png",
			tags: ["video", "loom", "recording"],
		},
		{
			id: "discover-skills",
			name: "Discover skills and more",
			description: "Explore more capabilities",
			category: "productivity",
			type: "atlassian",
			icon: "smart-link-embed",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["discover", "explore", "skills"],
		},
		{
			id: "set-reminder",
			name: "Set reminder",
			description: "Create a task reminder",
			category: "productivity",
			type: "atlassian",
			icon: "notification",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["reminder", "task", "alert"],
		},
		{
			id: "create-task",
			name: "Create task",
			description: "Add a new task to your list",
			category: "productivity",
			type: "atlassian",
			icon: "task-to-do",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["task", "todo", "create"],
		},
		{
			id: "track-time",
			name: "Track time",
			description: "Log time spent on work",
			category: "productivity",
			type: "atlassian",
			icon: "clock",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["time", "tracking", "logging"],
		},
		{
			id: "generate-report",
			name: "Generate report",
			description: "Create a summary report",
			category: "productivity",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["report", "summary", "analytics"],
		},
		{
			id: "analyze-sentiment",
			name: "Analyze sentiment",
			description: "Understand emotional tone",
			category: "analysis",
			type: "atlassian",
			icon: "sort-ascending",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["sentiment", "analysis", "emotion"],
		},
		{
			id: "extract-data",
			name: "Extract data",
			description: "Pull key information out",
			category: "analysis",
			type: "atlassian",
			icon: "copy",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["extract", "data", "information"],
		},
		{
			id: "compare-versions",
			name: "Compare versions",
			description: "See what changed between versions",
			category: "analysis",
			type: "atlassian",
			icon: "filter",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["compare", "diff", "versions"],
		},
		{
			id: "generate-insights",
			name: "Generate insights",
			description: "Get actionable insights from data",
			category: "analysis",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["insights", "analysis", "intelligence"],
		},
		{
			id: "create-project",
			name: "Create project",
			description: "Start a new project workspace",
			category: "project-management",
			type: "atlassian",
			icon: "project",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["project", "create", "workspace"],
		},
		{
			id: "create-roadmap",
			name: "Create roadmap",
			description: "Plan your product roadmap",
			category: "project-management",
			type: "atlassian",
			icon: "roadmap",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["roadmap", "planning", "strategy"],
		},
		{
			id: "create-sprint",
			name: "Create sprint",
			description: "Set up a new sprint",
			category: "project-management",
			type: "atlassian",
			icon: "sprint",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["sprint", "agile", "planning"],
		},
		{
			id: "create-epic",
			name: "Create epic",
			description: "Define a large work item",
			category: "project-management",
			type: "atlassian",
			icon: "epic",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["epic", "planning", "work-item"],
		},
		{
			id: "set-milestone",
			name: "Set milestone",
			description: "Mark important project milestones",
			category: "project-management",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["milestone", "tracking", "goals"],
		},
		{
			id: "track-progress",
			name: "Track progress",
			description: "Monitor project progress and status",
			category: "project-management",
			type: "atlassian",
			icon: "dashboard",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["progress", "tracking", "status"],
		},
		{
			id: "create-document",
			name: "Create document",
			description: "Generate a new document",
			category: "administrative-tools",
			type: "atlassian",
			icon: "file",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["document", "create", "file"],
		},
		{
			id: "organize-folder",
			name: "Organize folder",
			description: "Structure files and folders",
			category: "administrative-tools",
			type: "atlassian",
			icon: "folder-closed",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["folder", "organize", "structure"],
		},
		{
			id: "configure-settings",
			name: "Configure settings",
			description: "Adjust system and workspace settings",
			category: "administrative-tools",
			type: "atlassian",
			icon: "settings",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["settings", "configure", "preferences"],
		},
		{
			id: "manage-permissions",
			name: "Manage permissions",
			description: "Control access and permissions",
			category: "administrative-tools",
			type: "atlassian",
			icon: "lock-unlocked",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["permissions", "access", "security"],
		},
		{
			id: "bulk-edit",
			name: "Bulk edit",
			description: "Edit multiple items at once",
			category: "administrative-tools",
			type: "atlassian",
			icon: "edit-bulk",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["bulk", "edit", "batch"],
		},
		{
			id: "export-data",
			name: "Export data",
			description: "Export information to files",
			category: "administrative-tools",
			type: "atlassian",
			icon: "cloud-arrow-up",
			collection: "General",
			fill: "color.icon.subtlest",
			tags: ["export", "data", "download"],
		},
		{
			id: "create-page",
			name: "Create page",
			description: "Start a new content page",
			category: "content-communication",
			type: "atlassian",
			icon: "file",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["page", "content", "create"],
		},
		{
			id: "share-content",
			name: "Share content",
			description: "Share pages and documents",
			category: "content-communication",
			type: "atlassian",
			icon: "share",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["share", "content", "collaboration"],
		},
		{
			id: "comment-thread",
			name: "Comment thread",
			description: "Start a discussion thread",
			category: "content-communication",
			type: "atlassian",
			icon: "chat-widget",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["comment", "discussion", "thread"],
		},
		{
			id: "mention-team",
			name: "Mention team",
			description: "Notify team members",
			category: "content-communication",
			type: "atlassian",
			icon: "people-group",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["mention", "notify", "team"],
		},
		{
			id: "create-template",
			name: "Create template",
			description: "Build reusable content templates",
			category: "content-communication",
			type: "atlassian",
			icon: "edit",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["template", "reusable", "content"],
		},
		{
			id: "publish-content",
			name: "Publish content",
			description: "Make content available to others",
			category: "content-communication",
			type: "atlassian",
			icon: "send",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["publish", "content", "share"],
		},
		{
			id: "create-dashboard",
			name: "Create dashboard",
			description: "Build a custom analytics dashboard",
			category: "data-analytics",
			type: "atlassian",
			icon: "dashboard",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["dashboard", "analytics", "visualization"],
		},
		{
			id: "analyze-trends",
			name: "Analyze trends",
			description: "Identify patterns and trends",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-bar",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["trends", "analysis", "patterns"],
		},
		{
			id: "query-database",
			name: "Query database",
			description: "Extract data from databases",
			category: "data-analytics",
			type: "atlassian",
			icon: "database",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["query", "database", "data"],
		},
		{
			id: "create-report",
			name: "Create report",
			description: "Generate detailed reports",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["report", "analytics", "data"],
		},
		{
			id: "visualize-data",
			name: "Visualize data",
			description: "Create charts and graphs",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-bar",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["visualize", "charts", "graphs"],
		},
		{
			id: "track-metrics",
			name: "Track metrics",
			description: "Monitor key performance indicators",
			category: "data-analytics",
			type: "atlassian",
			icon: "dashboard",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			tags: ["metrics", "kpi", "tracking"],
		},
		{
			id: "create-branch",
			name: "Create branch",
			description: "Start a new code branch",
			category: "software-development",
			type: "atlassian",
			icon: "branch",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["branch", "git", "code"],
		},
		{
			id: "review-code",
			name: "Review code",
			description: "Submit code for review",
			category: "software-development",
			type: "atlassian",
			icon: "edit",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["review", "code", "pr"],
		},
		{
			id: "run-tests",
			name: "Run tests",
			description: "Execute test suites",
			category: "software-development",
			type: "atlassian",
			icon: "screen",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["tests", "testing", "qa"],
		},
		{
			id: "deploy-release",
			name: "Deploy release",
			description: "Deploy code to production",
			category: "software-development",
			type: "atlassian",
			icon: "cloud-arrow-up",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["deploy", "release", "production"],
		},
		{
			id: "track-bug",
			name: "Track bug",
			description: "Report and track bugs",
			category: "software-development",
			type: "atlassian",
			icon: "bug",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["bug", "issue", "tracking"],
		},
		{
			id: "view-code",
			name: "View code",
			description: "Browse source code",
			category: "software-development",
			type: "atlassian",
			icon: "angle-brackets",
			collection: "Software",
			fill: "color.icon.accent.lime",
			tags: ["code", "source", "browse"],
		},
		{
			id: "create-ticket",
			name: "Create ticket",
			description: "Open a support ticket",
			category: "it-support-service",
			type: "atlassian",
			icon: "bug",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["ticket", "support", "issue"],
		},
		{
			id: "resolve-incident",
			name: "Resolve incident",
			description: "Close and resolve incidents",
			category: "it-support-service",
			type: "atlassian",
			icon: "alert",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["incident", "resolve", "support"],
		},
		{
			id: "monitor-system",
			name: "Monitor system",
			description: "Track system health and performance",
			category: "it-support-service",
			type: "atlassian",
			icon: "screen",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["monitor", "system", "health"],
		},
		{
			id: "escalate-issue",
			name: "Escalate issue",
			description: "Escalate to higher support tier",
			category: "it-support-service",
			type: "atlassian",
			icon: "alert",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["escalate", "support", "priority"],
		},
		{
			id: "update-status",
			name: "Update status",
			description: "Update ticket or issue status",
			category: "it-support-service",
			type: "atlassian",
			icon: "edit",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["status", "update", "ticket"],
		},
		{
			id: "provide-support",
			name: "Provide support",
			description: "Offer help and assistance",
			category: "it-support-service",
			type: "atlassian",
			icon: "support",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["support", "help", "assistance"],
		},
		{
			id: "create-diagram",
			name: "Create diagram",
			description: "Design visual diagrams",
			category: "design-diagramming",
			type: "atlassian",
			icon: "data-flow",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["diagram", "design", "visual"],
		},
		{
			id: "design-mockup",
			name: "Design mockup",
			description: "Create design mockups",
			category: "design-diagramming",
			type: "atlassian",
			icon: "pen",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["mockup", "design", "ui"],
		},
		{
			id: "color-palette",
			name: "Color palette",
			description: "Apply color schemes",
			category: "design-diagramming",
			type: "atlassian",
			icon: "paint-bucket",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["color", "palette", "design"],
		},
		{
			id: "add-image",
			name: "Add image",
			description: "Insert images and graphics",
			category: "design-diagramming",
			type: "atlassian",
			icon: "image-fullscreen",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["image", "graphics", "visual"],
		},
		{
			id: "create-wireframe",
			name: "Create wireframe",
			description: "Design layout wireframes",
			category: "design-diagramming",
			type: "atlassian",
			icon: "panel-right",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["wireframe", "layout", "design"],
		},
		{
			id: "export-design",
			name: "Export design",
			description: "Export design assets",
			category: "design-diagramming",
			type: "atlassian",
			icon: "cloud-arrow-up",
			collection: "Product",
			fill: "color.icon.accent.purple",
			tags: ["export", "design", "assets"],
		},
		{
			id: "audit-security",
			name: "Audit security",
			description: "Perform security audits",
			category: "security-compliance",
			type: "atlassian",
			icon: "shield",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["security", "audit", "compliance"],
		},
		{
			id: "manage-access",
			name: "Manage access",
			description: "Control user access rights",
			category: "security-compliance",
			type: "atlassian",
			icon: "lock-unlocked",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["access", "security", "permissions"],
		},
		{
			id: "check-compliance",
			name: "Check compliance",
			description: "Verify compliance requirements",
			category: "security-compliance",
			type: "atlassian",
			icon: "component",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["compliance", "audit", "requirements"],
		},
		{
			id: "generate-key",
			name: "Generate key",
			description: "Create security keys and tokens",
			category: "security-compliance",
			type: "atlassian",
			icon: "key-result",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["key", "security", "token"],
		},
		{
			id: "scan-vulnerabilities",
			name: "Scan vulnerabilities",
			description: "Detect security vulnerabilities",
			category: "security-compliance",
			type: "atlassian",
			icon: "shield",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["vulnerability", "security", "scan"],
		},
		{
			id: "enforce-policy",
			name: "Enforce policy",
			description: "Apply security policies",
			category: "security-compliance",
			type: "atlassian",
			icon: "component",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["policy", "security", "enforcement"],
		},
		{
			id: "onboard-employee",
			name: "Onboard employee",
			description: "Start employee onboarding process",
			category: "hr-team-building",
			type: "atlassian",
			icon: "person",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["onboard", "employee", "hr"],
		},
		{
			id: "schedule-review",
			name: "Schedule review",
			description: "Set up performance reviews",
			category: "hr-team-building",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["review", "performance", "hr"],
		},
		{
			id: "collect-feedback",
			name: "Collect feedback",
			description: "Gather team feedback",
			category: "hr-team-building",
			type: "atlassian",
			icon: "feedback",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["feedback", "team", "hr"],
		},
		{
			id: "organize-team",
			name: "Organize team",
			description: "Manage team structure",
			category: "hr-team-building",
			type: "atlassian",
			icon: "people-group",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["team", "organize", "structure"],
		},
		{
			id: "plan-event",
			name: "Plan event",
			description: "Organize team events",
			category: "hr-team-building",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["event", "planning", "team"],
		},
		{
			id: "track-goals",
			name: "Track goals",
			description: "Monitor team and individual goals",
			category: "hr-team-building",
			type: "atlassian",
			icon: "key-result",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			tags: ["goals", "tracking", "okr"],
		},
		{
			id: "create-lead",
			name: "Create lead",
			description: "Add a new sales lead",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "person",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["lead", "sales", "customer"],
		},
		{
			id: "track-deal",
			name: "Track deal",
			description: "Monitor sales opportunities",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "chart-bar",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["deal", "sales", "opportunity"],
		},
		{
			id: "contact-customer",
			name: "Contact customer",
			description: "Reach out to customers",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "phone",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["contact", "customer", "communication"],
		},
		{
			id: "send-email",
			name: "Send email",
			description: "Send email to customers",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "email",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["email", "customer", "communication"],
		},
		{
			id: "rate-customer",
			name: "Rate customer",
			description: "Record customer ratings",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "scales",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["rating", "customer", "feedback"],
		},
		{
			id: "manage-account",
			name: "Manage account",
			description: "Handle customer accounts",
			category: "sales-customer-relations",
			type: "atlassian",
			icon: "person",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			tags: ["account", "customer", "management"],
		},
	],
};
