// Type definitions
export interface Skill {
	id: string;
	name: string;
	description: string;
	category: string;
	type: "atlassian" | "non-atlassian";
	icon: string; // Icon identifier from ADS icon library
	collection: string; // Collection name (Teamwork, Strategy, Service, Software, Product, General)
	fill: string; // Color token for icon fill (e.g., "color.icon.accent.blue")
	tags: string[]; // Array of tags for search and categorization
	appName: string; // App/product name (e.g., Jira, Confluence, Slack, GitHub); fallback to Atlassian when no specific product applies
	appLogo: string; // App logo URL (SVG or image file path)
	rating: number; // Rating out of 5 (e.g., 4.5)
	usageCount: number; // Total number of times skill has been used (e.g., 1432)
	mcpServer?: string; // MCP server name if skill is from MCP (e.g., "GitHub", "HubSpot", "Figma", "Box", "Asana")
}

export interface SkillCategory {
	id: string;
	name: string;
	description?: string;
}

export interface SkillsData {
	categories: SkillCategory[];
	skills: Skill[];
}

// Data
export const skillsData: SkillsData = {
	categories: [
		{
			id: "content-management",
			name: "Content Management",
			description: "Skills for creating, editing, organizing, and managing content across documents, wikis, and knowledge bases",
		},
		{
			id: "communication-collaboration",
			name: "Communication & Collaboration",
			description: "Skills for team communication, meetings, notifications, and collaborative workflows",
		},
		{
			id: "productivity-automation",
			name: "Productivity & Automation",
			description: "Skills for automating repetitive tasks, workflows, and improving personal/team productivity",
		},
		{
			id: "data-analytics",
			name: "Data & Analytics",
			description: "Skills for retrieving, analyzing, visualizing, and reporting on data from various sources",
		},
		{
			id: "project-management",
			name: "Project Management",
			description: "Skills for planning, tracking, and managing projects, tasks, timelines, and resources",
		},
		{
			id: "software-development",
			name: "Software Development",
			description: "Skills for code management, development workflows, CI/CD, and technical operations",
		},
		{
			id: "design-visualization",
			name: "Design & Visualization",
			description: "Skills for creating designs, mockups, diagrams, and visual representations",
		},
		{
			id: "security-compliance",
			name: "Security & Compliance",
			description: "Skills for security monitoring, compliance checks, access management, and audit processes",
		},
		{
			id: "business-operations",
			name: "Business Operations",
			description: "Skills for business processes, HR, finance, and operational workflows",
		},
		{
			id: "infrastructure-support",
			name: "Infrastructure & Support",
			description: "Skills for IT infrastructure, monitoring, support tickets, and system maintenance",
		},
	],
	skills: [
		{
			id: "summarize-page",
			name: "Summarize page",
			description: "Get the key points quickly",
			category: "content-management",
			type: "atlassian",
			icon: "align-text-left",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["summarize", "content", "quick-read"],
			rating: 4.0,
			usageCount: 1680,
		},
		{
			id: "summarize-changes",
			name: "Summarize changes",
			description: "See what's been updated",
			category: "content-management",
			type: "atlassian",
			icon: "clock",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["summarize", "changes", "updates"],
			rating: 4.6,
			usageCount: 1461,
		},
		{
			id: "change-tone",
			name: "Change tone",
			description: "Adjust the mood and style",
			category: "content-management",
			type: "atlassian",
			icon: "microphone",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["tone", "writing", "style"],
			rating: 3.3,
			usageCount: 2267,
		},
		{
			id: "translate",
			name: "Translate text",
			description: "Translate text to another language.",
			category: "content-management",
			type: "atlassian",
			icon: "translate",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["translation", "language", "multilingual"],
			rating: 3.6,
			usageCount: 517,
		},
		{
			id: "expand-text",
			name: "Expand text",
			description: "Make your content more detailed",
			category: "content-management",
			type: "atlassian",
			icon: "expand-horizontal",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["expand", "detail", "verbose"],
			rating: 3.2,
			usageCount: 1676,
		},
		{
			id: "make-shorter",
			name: "Shorten text",
			description: "Make the content more concise and brief.",
			category: "content-management",
			type: "atlassian",
			icon: "shrink-horizontal",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["shorten", "concise", "brief"],
			rating: 4.6,
			usageCount: 2801,
		},
		{
			id: "fix-grammar",
			name: "Correct grammar",
			description: "Correct spelling and grammar errors in the text.",
			category: "content-management",
			type: "atlassian",
			icon: "text-spellcheck",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["grammar", "spellcheck", "editing"],
			rating: 4.1,
			usageCount: 1471,
		},
		{
			id: "send-message",
			name: "Send message",
			description: "Send a message to team members.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "send",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Slack.svg",
			appName: "Slack",
			tags: ["message", "communication", "share"],
			rating: 4.8,
			usageCount: 2187,
		},
		{
			id: "schedule-meeting",
			name: "Schedule meeting",
			description: "Schedule a meeting with team members.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Outlook.svg",
			appName: "Microsoft Outlook",
			tags: ["meeting", "calendar", "schedule"],
			rating: 3.8,
			usageCount: 2565,
		},
		{
			id: "create-poll",
			name: "Create poll",
			description: "Create a poll to get feedback from the team.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Teams.svg",
			appName: "Microsoft Teams",
			tags: ["poll", "survey", "feedback"],
			rating: 3.4,
			usageCount: 2396,
		},
		{
			id: "share-screen",
			name: "Share screen",
			description: "Share your screen with others.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "screen-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Loom.svg",
			appName: "Loom",
			tags: ["screen", "presentation", "share"],
			rating: 3.2,
			usageCount: 984,
		},
		{
			id: "record-audio-note",
			name: "Record audio note",
			description: "Record an audio note for the team.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "audio",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Loom.svg",
			appName: "Loom",
			tags: ["audio", "voice", "recording"],
			rating: 3.2,
			usageCount: 2787,
		},
		{
			id: "turn-into-loom",
			name: "Create Loom video",
			description: "Create a Loom video from the content.",
			category: "communication-collaboration",
			type: "non-atlassian",
			icon: "video",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/Loom.svg",
			appName: "Loom",
			tags: ["video", "loom", "recording"],
			rating: 4.8,
			usageCount: 2065,
		},
		{
			id: "set-reminder",
			name: "Set reminder",
			description: "Set a reminder for a task or deadline.",
			category: "productivity-automation",
			type: "atlassian",
			icon: "notification",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Trello.svg",
			appName: "Trello",
			tags: ["reminder", "task", "alert"],
			rating: 4.1,
			usageCount: 1664,
		},
		{
			id: "create-task",
			name: "Create task",
			description: "Create a new task for the project.",
			category: "productivity-automation",
			type: "atlassian",
			icon: "task-to-do",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["task", "todo", "create"],
			rating: 4.5,
			usageCount: 2846,
		},
		{
			id: "track-time",
			name: "Track time",
			description: "Track time spent on work tasks.",
			category: "productivity-automation",
			type: "atlassian",
			icon: "clock",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["time", "tracking", "logging"],
			rating: 4.2,
			usageCount: 2798,
		},
		{
			id: "generate-report",
			name: "Generate report",
			description: "Generate a summary report from the data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["report", "summary", "analytics"],
			rating: 4.8,
			usageCount: 743,
		},
		{
			id: "analyze-sentiment",
			name: "Analyze sentiment",
			description: "Analyze the emotional tone of the text.",
			category: "data-analytics",
			type: "atlassian",
			icon: "sort-ascending",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["sentiment", "analysis", "emotion"],
			rating: 4.2,
			usageCount: 2579,
		},
		{
			id: "extract-data",
			name: "Extract data",
			description: "Extract key information from the data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "copy",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["extract", "data", "information"],
			rating: 4.2,
			usageCount: 2274,
		},
		{
			id: "compare-versions",
			name: "Compare versions",
			description: "Compare different versions to see changes.",
			category: "data-analytics",
			type: "atlassian",
			icon: "filter",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["compare", "diff", "versions"],
			rating: 4.6,
			usageCount: 2834,
		},
		{
			id: "generate-insights",
			name: "Generate insights",
			description: "Generate actionable insights from the data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Goals.svg",
			appName: "Goals",
			tags: ["insights", "analysis", "intelligence"],
			rating: 3.1,
			usageCount: 2676,
		},
		{
			id: "create-project",
			name: "Create project",
			description: "Start a new project workspace",
			category: "project-management",
			type: "atlassian",
			icon: "project",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["project", "create", "workspace"],
			rating: 3.2,
			usageCount: 2390,
		},
		{
			id: "create-roadmap",
			name: "Create roadmap",
			description: "Plan your product roadmap",
			category: "project-management",
			type: "atlassian",
			icon: "roadmap",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Goals.svg",
			appName: "Goals",
			tags: ["roadmap", "planning", "strategy"],
			rating: 3.5,
			usageCount: 2287,
		},
		{
			id: "create-sprint",
			name: "Create sprint",
			description: "Set up a new sprint",
			category: "project-management",
			type: "atlassian",
			icon: "sprint",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["sprint", "agile", "planning"],
			rating: 4.1,
			usageCount: 553,
		},
		{
			id: "create-epic",
			name: "Create epic",
			description: "Define a large work item",
			category: "project-management",
			type: "atlassian",
			icon: "epic",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["epic", "planning", "work-item"],
			rating: 3.1,
			usageCount: 1434,
		},
		{
			id: "set-milestone",
			name: "Set milestone",
			description: "Mark important project milestones",
			category: "project-management",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Goals.svg",
			appName: "Goals",
			tags: ["milestone", "tracking", "goals"],
			rating: 3.5,
			usageCount: 1098,
		},
		{
			id: "track-progress",
			name: "Track progress",
			description: "Monitor project progress and status",
			category: "project-management",
			type: "atlassian",
			icon: "dashboard",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["progress", "tracking", "status"],
			rating: 4.0,
			usageCount: 580,
		},
		{
			id: "create-document",
			name: "Create document",
			description: "Create a new document for the team.",
			category: "content-management",
			type: "atlassian",
			icon: "file",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["document", "create", "file"],
			rating: 4.7,
			usageCount: 717,
		},
		{
			id: "organize-folder",
			name: "Organize folder",
			description: "Organize files and folders in the workspace.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "folder-closed",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/GDrive.svg",
			appName: "Google Drive",
			tags: ["folder", "organize", "structure"],
			rating: 4.1,
			usageCount: 1225,
		},
		{
			id: "configure-settings",
			name: "Configure settings",
			description: "Configure system and workspace settings.",
			category: "business-operations",
			type: "atlassian",
			icon: "settings",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/Atlassian.svg",
			appName: "Atlassian",
			tags: ["settings", "configure", "preferences"],
			rating: 4.5,
			usageCount: 1934,
		},
		{
			id: "manage-permissions",
			name: "Manage permissions",
			description: "Manage access and permissions for users.",
			category: "security-compliance",
			type: "atlassian",
			icon: "lock-unlocked",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["permissions", "access", "security"],
			rating: 3.4,
			usageCount: 1194,
		},
		{
			id: "bulk-edit",
			name: "Bulk edit",
			description: "Edit multiple items at once in bulk.",
			category: "productivity-automation",
			type: "atlassian",
			icon: "edit-bulk",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["bulk", "edit", "batch"],
			rating: 3.4,
			usageCount: 2779,
		},
		{
			id: "export-data",
			name: "Export data",
			description: "Export data to files for analysis.",
			category: "data-analytics",
			type: "atlassian",
			icon: "cloud-arrow-up",
			collection: "General",
			fill: "color.icon.subtlest",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["export", "data", "download"],
			rating: 4.8,
			usageCount: 1581,
		},
		{
			id: "create-page",
			name: "Create page",
			description: "Create a new content page.",
			category: "content-management",
			type: "atlassian",
			icon: "file",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["page", "content", "create"],
			rating: 3.8,
			usageCount: 1708,
		},
		{
			id: "share-content",
			name: "Share content",
			description: "Share content with team members.",
			category: "communication-collaboration",
			type: "atlassian",
			icon: "share",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["share", "content", "collaboration"],
			rating: 3.7,
			usageCount: 609,
		},
		{
			id: "comment-thread",
			name: "Start comment thread",
			description: "Start a discussion thread on the content.",
			category: "communication-collaboration",
			type: "atlassian",
			icon: "chat-widget",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["comment", "discussion", "thread"],
			rating: 4.0,
			usageCount: 1310,
		},
		{
			id: "mention-team",
			name: "Mention team",
			description: "Mention team members in the content.",
			category: "communication-collaboration",
			type: "atlassian",
			icon: "people-group",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["mention", "notify", "team"],
			rating: 3.1,
			usageCount: 2734,
		},
		{
			id: "create-template",
			name: "Create template",
			description: "Create a reusable content template.",
			category: "content-management",
			type: "atlassian",
			icon: "edit",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["template", "reusable", "content"],
			rating: 4.7,
			usageCount: 585,
		},
		{
			id: "publish-content",
			name: "Publish content",
			description: "Publish content to make it available to others.",
			category: "content-management",
			type: "atlassian",
			icon: "send",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Confluence.svg",
			appName: "Confluence",
			tags: ["publish", "content", "share"],
			rating: 4.1,
			usageCount: 577,
		},
		{
			id: "create-dashboard",
			name: "Create dashboard",
			description: "Create a custom analytics dashboard.",
			category: "data-analytics",
			type: "atlassian",
			icon: "dashboard",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["dashboard", "analytics", "visualization"],
			rating: 4.7,
			usageCount: 2334,
		},
		{
			id: "analyze-trends",
			name: "Analyze trends",
			description: "Analyze patterns and trends in the data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-bar",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["trends", "analysis", "patterns"],
			rating: 4.6,
			usageCount: 2160,
		},
		{
			id: "query-database",
			name: "Query database",
			description: "Query a database to extract data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "database",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["query", "database", "data"],
			rating: 4.1,
			usageCount: 1202,
		},
		{
			id: "create-report",
			name: "Create report",
			description: "Create a detailed report from the data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-pie",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["report", "analytics", "data"],
			rating: 4.6,
			usageCount: 874,
		},
		{
			id: "visualize-data",
			name: "Visualize data",
			description: "Create charts and graphs to visualize data.",
			category: "data-analytics",
			type: "atlassian",
			icon: "chart-bar",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["visualize", "charts", "graphs"],
			rating: 5.0,
			usageCount: 1605,
		},
		{
			id: "track-metrics",
			name: "Track metrics",
			description: "Track key performance indicators and metrics.",
			category: "data-analytics",
			type: "atlassian",
			icon: "dashboard",
			collection: "Strategy",
			fill: "color.icon.accent.orange",
			appLogo: "/app-logo/Goals.svg",
			appName: "Goals",
			tags: ["metrics", "kpi", "tracking"],
			rating: 4.8,
			usageCount: 1090,
		},
		{
			id: "create-branch",
			name: "Create branch",
			description: "Start a new code branch",
			category: "software-development",
			type: "atlassian",
			icon: "branch",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Bitbucket.svg",
			appName: "Bitbucket",
			tags: ["branch", "git", "code"],
			rating: 3.7,
			usageCount: 1275,
		},
		{
			id: "review-code",
			name: "Review code",
			description: "Submit code for review",
			category: "software-development",
			type: "atlassian",
			icon: "edit",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Bitbucket.svg",
			appName: "Bitbucket",
			tags: ["review", "code", "pr"],
			rating: 4.9,
			usageCount: 2035,
		},
		{
			id: "run-tests",
			name: "Run tests",
			description: "Execute test suites",
			category: "software-development",
			type: "atlassian",
			icon: "screen",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Bitbucket.svg",
			appName: "Bitbucket",
			tags: ["tests", "testing", "qa"],
			rating: 4.1,
			usageCount: 1756,
		},
		{
			id: "deploy-release",
			name: "Deploy release",
			description: "Deploy code to production",
			category: "software-development",
			type: "atlassian",
			icon: "cloud-arrow-up",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Bitbucket.svg",
			appName: "Bitbucket",
			tags: ["deploy", "release", "production"],
			rating: 3.1,
			usageCount: 2927,
		},
		{
			id: "track-bug",
			name: "Track bug",
			description: "Report and track bugs",
			category: "software-development",
			type: "atlassian",
			icon: "bug",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Jira.svg",
			appName: "Jira",
			tags: ["bug", "issue", "tracking"],
			rating: 3.4,
			usageCount: 1899,
		},
		{
			id: "view-code",
			name: "View code",
			description: "Browse source code",
			category: "software-development",
			type: "atlassian",
			icon: "angle-brackets",
			collection: "Software",
			fill: "color.icon.accent.lime",
			appLogo: "/app-logo/Bitbucket.svg",
			appName: "Bitbucket",
			tags: ["code", "source", "browse"],
			rating: 3.2,
			usageCount: 833,
		},
		{
			id: "create-ticket",
			name: "Create ticket",
			description: "Create a support ticket for the issue.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "bug",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["ticket", "support", "issue"],
			rating: 4.6,
			usageCount: 750,
		},
		{
			id: "resolve-incident",
			name: "Resolve incident",
			description: "Resolve and close support incidents.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "alert",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["incident", "resolve", "support"],
			rating: 4.4,
			usageCount: 1522,
		},
		{
			id: "monitor-system",
			name: "Monitor system",
			description: "Monitor system health and performance.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "screen",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["monitor", "system", "health"],
			rating: 4.1,
			usageCount: 2161,
		},
		{
			id: "escalate-issue",
			name: "Escalate issue",
			description: "Escalate issues to a higher support tier.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "alert",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["escalate", "support", "priority"],
			rating: 4.6,
			usageCount: 1241,
		},
		{
			id: "update-status",
			name: "Update status",
			description: "Update the status of tickets or issues.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "edit",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["status", "update", "ticket"],
			rating: 3.3,
			usageCount: 1046,
		},
		{
			id: "provide-support",
			name: "Provide support",
			description: "Provide help and assistance to users.",
			category: "infrastructure-support",
			type: "atlassian",
			icon: "support",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/CSM.svg",
			appName: "Customer Service Management",
			tags: ["support", "help", "assistance"],
			rating: 4.9,
			usageCount: 2264,
		},
		{
			id: "create-diagram",
			name: "Create diagram",
			description: "Create visual diagrams for documentation.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "data-flow",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["diagram", "design", "visual"],
			rating: 3.2,
			usageCount: 1465,
		},
		{
			id: "design-mockup",
			name: "Design mockup",
			description: "Create design mockups for the interface.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "pen",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["mockup", "design", "ui"],
			rating: 4.1,
			usageCount: 852,
		},
		{
			id: "color-palette",
			name: "Apply color palette",
			description: "Apply a color scheme to the design.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "paint-bucket",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["color", "palette", "design"],
			rating: 4.5,
			usageCount: 2913,
		},
		{
			id: "add-image",
			name: "Add image",
			description: "Add images and graphics to the content.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "image-fullscreen",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["image", "graphics", "visual"],
			rating: 4.9,
			usageCount: 695,
		},
		{
			id: "create-wireframe",
			name: "Create wireframe",
			description: "Create layout wireframes for the design.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "panel-right",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["wireframe", "layout", "design"],
			rating: 4.4,
			usageCount: 2938,
		},
		{
			id: "export-design",
			name: "Export design",
			description: "Export design assets to files.",
			category: "design-visualization",
			type: "non-atlassian",
			icon: "cloud-arrow-up",
			collection: "Product",
			fill: "color.icon.accent.purple",
			appLogo: "/app-logo/Figma.svg",
			appName: "Figma",
			mcpServer: "Figma",
			tags: ["export", "design", "assets"],
			rating: 4.5,
			usageCount: 1665,
		},
		{
			id: "audit-security",
			name: "Audit security",
			description: "Perform security audits",
			category: "security-compliance",
			type: "atlassian",
			icon: "shield",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/CSM.svg",
			appName: "Customer Service Management",
			tags: ["security", "audit", "compliance"],
			rating: 4.0,
			usageCount: 2628,
		},
		{
			id: "manage-access",
			name: "Manage access",
			description: "Control user access rights",
			category: "security-compliance",
			type: "atlassian",
			icon: "lock-unlocked",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["access", "security", "permissions"],
			rating: 4.2,
			usageCount: 725,
		},
		{
			id: "check-compliance",
			name: "Check compliance",
			description: "Verify compliance requirements",
			category: "security-compliance",
			type: "atlassian",
			icon: "component",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/CSM.svg",
			appName: "Customer Service Management",
			tags: ["compliance", "audit", "requirements"],
			rating: 5.0,
			usageCount: 2257,
		},
		{
			id: "generate-key",
			name: "Generate key",
			description: "Create security keys and tokens",
			category: "security-compliance",
			type: "atlassian",
			icon: "key-result",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/JSM.svg",
			appName: "Jira Service Management",
			tags: ["key", "security", "token"],
			rating: 4.6,
			usageCount: 2874,
		},
		{
			id: "scan-vulnerabilities",
			name: "Scan vulnerabilities",
			description: "Detect security vulnerabilities",
			category: "security-compliance",
			type: "atlassian",
			icon: "shield",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/CSM.svg",
			appName: "Customer Service Management",
			tags: ["vulnerability", "security", "scan"],
			rating: 3.3,
			usageCount: 650,
		},
		{
			id: "enforce-policy",
			name: "Enforce policy",
			description: "Apply security policies",
			category: "security-compliance",
			type: "atlassian",
			icon: "component",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/CSM.svg",
			appName: "Customer Service Management",
			tags: ["policy", "security", "enforcement"],
			rating: 3.2,
			usageCount: 1836,
		},
		{
			id: "onboard-employee",
			name: "Onboard employee",
			description: "Start the employee onboarding process.",
			category: "business-operations",
			type: "atlassian",
			icon: "person",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Talent.svg",
			appName: "Talent",
			tags: ["onboard", "employee", "hr"],
			rating: 3.3,
			usageCount: 1637,
		},
		{
			id: "schedule-review",
			name: "Schedule review",
			description: "Schedule a performance review meeting.",
			category: "business-operations",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Talent.svg",
			appName: "Talent",
			tags: ["review", "performance", "hr"],
			rating: 3.0,
			usageCount: 1379,
		},
		{
			id: "collect-feedback",
			name: "Collect feedback",
			description: "Collect feedback from team members.",
			category: "business-operations",
			type: "atlassian",
			icon: "feedback",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Talent.svg",
			appName: "Talent",
			tags: ["feedback", "team", "hr"],
			rating: 4.1,
			usageCount: 2555,
		},
		{
			id: "organize-team",
			name: "Organize team",
			description: "Organize the team structure and roles.",
			category: "business-operations",
			type: "atlassian",
			icon: "people-group",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Projects.svg",
			appName: "Projects",
			tags: ["team", "organize", "structure"],
			rating: 4.5,
			usageCount: 603,
		},
		{
			id: "plan-event",
			name: "Plan event",
			description: "Plan and organize team events.",
			category: "business-operations",
			type: "atlassian",
			icon: "calendar-plus",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Trello.svg",
			appName: "Trello",
			tags: ["event", "planning", "team"],
			rating: 4.3,
			usageCount: 2018,
		},
		{
			id: "track-goals",
			name: "Track goals",
			description: "Track team and individual goals.",
			category: "business-operations",
			type: "atlassian",
			icon: "key-result",
			collection: "Teamwork",
			fill: "color.icon.accent.blue",
			appLogo: "/app-logo/Goals.svg",
			appName: "Goals",
			tags: ["goals", "tracking", "okr"],
			rating: 3.8,
			usageCount: 1994,
		},
		{
			id: "create-lead",
			name: "Create lead",
			description: "Create a new sales lead in the system.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "person",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Salesforce.svg",
			appName: "Salesforce",
			tags: ["lead", "sales", "customer"],
			rating: 4.3,
			usageCount: 1527,
		},
		{
			id: "track-deal",
			name: "Track deal",
			description: "Track sales opportunities and deals.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "chart-bar",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Salesforce.svg",
			appName: "Salesforce",
			tags: ["deal", "sales", "opportunity"],
			rating: 4.6,
			usageCount: 2879,
		},
		{
			id: "contact-customer",
			name: "Contact customer",
			description: "Contact customers for follow-up.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "phone",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Salesforce.svg",
			appName: "Salesforce",
			tags: ["contact", "customer", "communication"],
			rating: 3.6,
			usageCount: 2355,
		},
		{
			id: "send-email",
			name: "Send email",
			description: "Send an email to customers.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "email",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Outlook.svg",
			appName: "Microsoft Outlook",
			tags: ["email", "customer", "communication"],
			rating: 3.7,
			usageCount: 1390,
		},
		{
			id: "rate-customer",
			name: "Rate customer",
			description: "Record customer ratings and feedback.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "scales",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Salesforce.svg",
			appName: "Salesforce",
			tags: ["rating", "customer", "feedback"],
			rating: 3.6,
			usageCount: 2444,
		},
		{
			id: "manage-account",
			name: "Manage account",
			description: "Manage customer accounts and information.",
			category: "business-operations",
			type: "non-atlassian",
			icon: "person",
			collection: "Service",
			fill: "color.icon.accent.yellow",
			appLogo: "/app-logo/Salesforce.svg",
			appName: "Salesforce",
			tags: ["account", "customer", "management"],
			rating: 3.5,
			usageCount: 1494,
		},
	],
};
